import type { UserComponent } from '@craftjs/core';
import type { ComponentDef, ResolverComponentName } from './types';
import { Button } from './components/input/Button';
import { CheckboxGroup } from './components/input/CheckboxGroup';
import { Container } from './components/container/Container';
import { Form } from './components/container/Form';
import { InputField } from './components/input/InputField';
import { NumberInput } from './components/input/NumberInput';
import { RadioGroup } from './components/input/RadioGroup';
import { StageRoot } from './components/container/StageRoot';
import { Text } from './components/display/Text';
import { ImageDisplay } from './components/display/ImageDisplay';
import { VideoDisplay } from './components/display/VideoDisplay';
import { MarkdownDisplay } from './components/display/MarkdownDisplay';
import { AudioDisplay } from './components/display/AudioDisplay';
import { CarouselDisplay } from './components/display/CarouselDisplay';
import { AudioRecorder } from './components/input/AudioRecorder';
import { VideoRecorder } from './components/input/VideoRecorder';
import { HorizontalList } from './components/container/HorizontalList';
import { VerticalList } from './components/container/VerticalList';
import { GridList } from './components/container/GridList';

import iconListHorizontal from '../assets/list-horizontal.svg';
import iconListVertical from '../assets/list-vertical.svg';
import iconListGrid from '../assets/list-grid.svg';
import iconText from '../assets/text.svg';
import iconAudio from '../assets/audio.svg';
import iconVideo from '../assets/video.svg';
import iconImage from '../assets/image.svg';
import iconCarousel from '../assets/carousel.svg';
import iconMarkdown from '../assets/markdown.svg';
import iconButton from '../assets/button.svg';
import iconInput from '../assets/input.svg';
import iconRadio from '../assets/radio.svg';
import iconCheckbox from '../assets/checkbox.svg';
import iconNumberInput from '../assets/number-input.svg';
import iconAudioRecord from '../assets/audio-record.svg';
import iconVideoRecord from '../assets/video-record.svg';
import iconForm from '../assets/form.svg';
import iconContainer from '../assets/container.svg';

export const CRAFT_COMPONENT_MIME = 'application/x-teamhelper-craft-component';

export const RESOLVER: Record<ResolverComponentName, UserComponent> = {
  StageRoot,
  Button,
  InputField,
  RadioGroup,
  CheckboxGroup,
  NumberInput,
  Text,
  ImageDisplay,
  VideoDisplay,
  MarkdownDisplay,
  AudioDisplay,
  CarouselDisplay,
  AudioRecorder,
  VideoRecorder,
  Container,
  Form,
  HorizontalList,
  VerticalList,
  GridList,
};

export type CraftComponentType = ResolverComponentName;

interface RegistryItem extends ComponentDef {
  craftType: CraftComponentType;
  defaultChildren?: ChildDragPayload[];
}

export interface ChildDragPayload {
  type: CraftComponentType;
  props: Record<string, unknown>;
  isCanvas?: boolean;
  defaultChildren?: ChildDragPayload[];
}

export interface ComponentDragPayload {
  type: CraftComponentType;
  props: Record<string, unknown>;
  isCanvas?: boolean;
  defaultChildren?: ChildDragPayload[];
}

const DEFAULT_TRANSFORM = {
  scale: 100,
  rotate: 0,
  translateX: 0,
  translateY: 0,
  skewX: 0,
  skewY: 0,
};

const createVerticalListItemChildren = (index: number): ChildDragPayload => ({
  type: 'Container',
  isCanvas: true,
  props: {
    verticalListRole: 'item',
    layout: {
      arrangement: 'horizontal',
      spacingMode: 'fixed',
      spacing: 12,
      distribution: 'center-left',
      columnDistribution: 'left',
    },
    positionType: 'relative',
    positionTop: 0,
    positionRight: 0,
    positionBottom: 0,
    positionLeft: 0,
    widthMode: 'fill',
    heightMode: 'fixed',
    width: 480,
    height: 84,
    sizeLimits: [],
    containerStyle: {
      background: '#111827',
      borderRadius: 8,
      padding: { top: 12, right: 12, bottom: 12, left: 12 },
      margin: 0,
      border: { width: 1, color: '#334155', style: 'solid' },
      shadow: null,
    },
    overflow: 'hidden',
    blur: null,
    transform: DEFAULT_TRANSFORM,
  },
  defaultChildren: [
    {
      type: 'ImageDisplay',
      props: {
        verticalListRole: 'item-image',
        sourceType: 'local',
        imageUrl: null,
        bindingField: '',
        fillMode: 'contain',
        forcePlaceholder: false,
        placeholderMode: 'image',
        placeholderText: '',
        positionType: 'relative',
        positionTop: 0,
        positionRight: 0,
        positionBottom: 0,
        positionLeft: 0,
        widthMode: 'fixed',
        heightMode: 'fixed',
        width: 56,
        height: 56,
        sizeLimits: [],
        containerStyle: {
          background: '#1f2937',
          borderRadius: 6,
          padding: 8,
          margin: 0,
          border: null,
          shadow: null,
        },
        blur: null,
        transform: DEFAULT_TRANSFORM,
      },
    },
    {
      type: 'Container',
      isCanvas: true,
      props: {
        verticalListRole: 'item-content',
        layout: {
          arrangement: 'vertical',
          spacingMode: 'fixed',
          spacing: 4,
          distribution: 'center-left',
          columnDistribution: 'left',
        },
        positionType: 'relative',
        positionTop: 0,
        positionRight: 0,
        positionBottom: 0,
        positionLeft: 0,
        widthMode: 'fill',
        heightMode: 'fill',
        width: 400,
        height: 56,
        sizeLimits: [],
        containerStyle: null,
        overflow: 'visible',
        blur: null,
        transform: DEFAULT_TRANSFORM,
      },
      defaultChildren: [
        {
          type: 'Text',
          props: {
            verticalListRole: 'item-title',
            text: `列表项 ${index}`,
            styleMode: 'custom',
            presetStyle: '20',
            fontSize: 16,
            fontWeight: 600,
            letterSpacing: 0,
            lineHeight: 20,
            textAlign: 'left',
            verticalAlign: 'center',
            color: '#ffffff',
            textShadow: null,
            maxLines: 1,
            positionType: 'relative',
            positionTop: 0,
            positionRight: 0,
            positionBottom: 0,
            positionLeft: 0,
            widthMode: 'fill',
            heightMode: 'fit-content',
            width: 360,
            height: 20,
            sizeLimits: [],
            containerStyle: null,
            overflow: 'hidden',
            transform: DEFAULT_TRANSFORM,
          },
        },
        {
          type: 'Text',
          props: {
            verticalListRole: 'item-description',
            text: '这是一个填充文本，这是一个填充文本。',
            styleMode: 'custom',
            presetStyle: '20',
            fontSize: 14,
            fontWeight: 400,
            letterSpacing: 0,
            lineHeight: 20,
            textAlign: 'left',
            verticalAlign: 'top',
            color: '#cbd5e1',
            textShadow: null,
            maxLines: 2,
            positionType: 'relative',
            positionTop: 0,
            positionRight: 0,
            positionBottom: 0,
            positionLeft: 0,
            widthMode: 'fill',
            heightMode: 'fit-content',
            width: 360,
            height: 40,
            sizeLimits: [],
            containerStyle: null,
            overflow: 'hidden',
            transform: DEFAULT_TRANSFORM,
          },
        },
      ],
    },
  ],
});

const createHorizontalListItemChildren = (index: number): ChildDragPayload => ({
  type: 'Container',
  isCanvas: true,
  props: {
    horizontalListRole: 'item',
    layout: {
      arrangement: 'vertical',
      spacingMode: 'fixed',
      spacing: 10,
      distribution: 'top-left',
      columnDistribution: 'left',
    },
    positionType: 'relative',
    positionTop: 0,
    positionRight: 0,
    positionBottom: 0,
    positionLeft: 0,
    widthMode: 'fixed',
    heightMode: 'fixed',
    width: 160,
    height: 272,
    sizeLimits: [],
    containerStyle: {
      background: '#111827',
      borderRadius: 8,
      padding: { top: 12, right: 12, bottom: 12, left: 12 },
      margin: 0,
      border: { width: 1, color: '#334155', style: 'solid' },
      shadow: null,
    },
    overflow: 'hidden',
    blur: null,
    transform: DEFAULT_TRANSFORM,
  },
  defaultChildren: [
    {
      type: 'ImageDisplay',
      props: {
        horizontalListRole: 'item-image',
        sourceType: 'local',
        imageUrl: null,
        bindingField: '',
        fillMode: 'contain',
        forcePlaceholder: false,
        placeholderMode: 'image',
        placeholderText: '',
        positionType: 'relative',
        positionTop: 0,
        positionRight: 0,
        positionBottom: 0,
        positionLeft: 0,
        widthMode: 'fill',
        heightMode: 'fixed',
        width: 136,
        height: 136,
        sizeLimits: [],
        containerStyle: {
          background: '#1f2937',
          borderRadius: 6,
          padding: 10,
          margin: 0,
          border: null,
          shadow: null,
        },
        blur: null,
        transform: DEFAULT_TRANSFORM,
      },
    },
    {
      type: 'Text',
      props: {
        horizontalListRole: 'item-title',
        text: `列表项 ${index}`,
        styleMode: 'custom',
        presetStyle: '20',
        fontSize: 16,
        fontWeight: 600,
        letterSpacing: 0,
        lineHeight: 20,
        textAlign: 'left',
        verticalAlign: 'center',
        color: '#ffffff',
        textShadow: null,
        maxLines: 1,
        positionType: 'relative',
        positionTop: 0,
        positionRight: 0,
        positionBottom: 0,
        positionLeft: 0,
        widthMode: 'fill',
        heightMode: 'fit-content',
        width: 136,
        height: 20,
        sizeLimits: [],
        containerStyle: null,
        overflow: 'hidden',
        transform: DEFAULT_TRANSFORM,
      },
    },
    {
      type: 'Text',
      props: {
        horizontalListRole: 'item-description',
        text: '这是一个填充文本，这是一个填充文本。',
        styleMode: 'custom',
        presetStyle: '20',
        fontSize: 14,
        fontWeight: 400,
        letterSpacing: 0,
        lineHeight: 20,
        textAlign: 'left',
        verticalAlign: 'top',
        color: '#cbd5e1',
        textShadow: null,
        maxLines: 3,
        positionType: 'relative',
        positionTop: 0,
        positionRight: 0,
        positionBottom: 0,
        positionLeft: 0,
        widthMode: 'fill',
        heightMode: 'fit-content',
        width: 136,
        height: 72,
        sizeLimits: [],
        containerStyle: null,
        overflow: 'hidden',
        transform: DEFAULT_TRANSFORM,
      },
    },
  ],
});

const createGridListItemChildren = (index: number): ChildDragPayload => ({
  type: 'Container',
  isCanvas: true,
  props: {
    gridListRole: 'item',
    layout: {
      arrangement: 'vertical',
      spacingMode: 'fixed',
      spacing: 16,
      distribution: 'top-center',
      columnDistribution: 'center',
    },
    positionType: 'relative',
    positionTop: 0,
    positionRight: 0,
    positionBottom: 0,
    positionLeft: 0,
    widthMode: 'fill',
    heightMode: 'fixed',
    width: 220,
    height: 260,
    sizeLimits: [],
    containerStyle: {
      background: '#111827',
      borderRadius: 12,
      padding: { top: 20, right: 20, bottom: 20, left: 20 },
      margin: 0,
      border: { width: 1, color: '#334155', style: 'solid' },
      shadow: null,
    },
    overflow: 'hidden',
    blur: null,
    transform: DEFAULT_TRANSFORM,
  },
  defaultChildren: [
    {
      type: 'ImageDisplay',
      props: {
        gridListRole: 'item-image',
        sourceType: 'local',
        imageUrl: null,
        bindingField: '',
        fillMode: 'contain',
        forcePlaceholder: false,
        placeholderMode: 'image',
        placeholderText: '',
        positionType: 'relative',
        positionTop: 0,
        positionRight: 0,
        positionBottom: 0,
        positionLeft: 0,
        widthMode: 'fixed',
        heightMode: 'fixed',
        width: 96,
        height: 96,
        sizeLimits: [],
        containerStyle: {
          background: '#2a303b',
          borderRadius: 8,
          padding: 12,
          margin: 0,
          border: null,
          shadow: null,
        },
        blur: null,
        transform: DEFAULT_TRANSFORM,
      },
    },
    {
      type: 'Text',
      props: {
        gridListRole: 'item-title',
        text: `标题${index}`,
        styleMode: 'custom',
        presetStyle: '20',
        fontSize: 18,
        fontWeight: 600,
        letterSpacing: 0,
        lineHeight: 24,
        textAlign: 'center',
        verticalAlign: 'center',
        color: '#ffffff',
        textShadow: null,
        maxLines: 1,
        positionType: 'relative',
        positionTop: 0,
        positionRight: 0,
        positionBottom: 0,
        positionLeft: 0,
        widthMode: 'fill',
        heightMode: 'fit-content',
        width: 180,
        height: 24,
        sizeLimits: [],
        containerStyle: null,
        overflow: 'hidden',
        transform: DEFAULT_TRANSFORM,
      },
    },
    {
      type: 'Text',
      props: {
        gridListRole: 'item-description',
        text: '这是一个填充文本',
        styleMode: 'custom',
        presetStyle: '20',
        fontSize: 14,
        fontWeight: 400,
        letterSpacing: 0,
        lineHeight: 20,
        textAlign: 'center',
        verticalAlign: 'top',
        color: '#cbd5e1',
        textShadow: null,
        maxLines: 2,
        positionType: 'relative',
        positionTop: 0,
        positionRight: 0,
        positionBottom: 0,
        positionLeft: 0,
        widthMode: 'fill',
        heightMode: 'fit-content',
        width: 180,
        height: 40,
        sizeLimits: [],
        containerStyle: null,
        overflow: 'hidden',
        transform: DEFAULT_TRANSFORM,
      },
    },
  ],
});

export const COMPONENT_REGISTRY: RegistryItem[] = [
  /* ---- 容器组件 ---- */
  {
    type: 'layout-container',
    craftType: 'Container',
    label: '容器',
    category: '容器组件',
    icon: iconContainer,
    description: '基础布局容器',
    isCanvas: true,
    defaultProps: {
      layout: { arrangement: 'vertical', spacingMode: 'fixed', spacing: 8, distribution: 'top-left', columnDistribution: 'left' },
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fixed',
      heightMode: 'fixed',
      width: 350,
      height: 180,
      sizeLimits: [],
      containerStyle: null,
      overflow: 'scroll',
      blur: null,
      transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
    },
  },

  /* ---- 列表组件 ---- */
  {
    type: 'list-horizontal',
    craftType: 'HorizontalList',
    label: '横向列表',
    category: '列表组件',
    icon: iconListHorizontal,
    description: '带标题与横向卡片项的列表',
    isCanvas: true,
    defaultProps: {
      title: '列表标题',
      itemSpacing: 12,
      showItemNumber: false,
      dataMode: 'expression',
      expression: '',
      layout: { arrangement: 'vertical', spacingMode: 'fixed', spacing: 12, distribution: 'top-left', columnDistribution: 'left' },
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fill',
      heightMode: 'fit-content',
      width: 520,
      height: 280,
      sizeLimits: [],
      containerStyle: null,
      overflow: 'scroll',
      blur: null,
      transform: DEFAULT_TRANSFORM,
    },
    defaultChildren: [
      {
        type: 'Text',
        props: {
          horizontalListRole: 'title',
          text: '列表标题',
          styleMode: 'custom',
          presetStyle: '24',
          fontSize: 24,
          fontWeight: 700,
          letterSpacing: 0,
          lineHeight: 32,
          textAlign: 'left',
          verticalAlign: 'center',
          color: '#ffffff',
          textShadow: null,
          maxLines: 1,
          positionType: 'relative',
          positionTop: 0,
          positionRight: 0,
          positionBottom: 0,
          positionLeft: 0,
          widthMode: 'fill',
          heightMode: 'fit-content',
          width: 520,
          height: 32,
          sizeLimits: [],
          containerStyle: null,
          overflow: 'hidden',
          transform: DEFAULT_TRANSFORM,
        },
      },
      {
        type: 'Container',
        isCanvas: true,
        props: {
          horizontalListRole: 'items',
          layout: {
            arrangement: 'horizontal',
            spacingMode: 'fixed',
            spacing: 12,
            distribution: 'top-left',
            columnDistribution: 'left',
          },
          positionType: 'relative',
          positionTop: 0,
          positionRight: 0,
          positionBottom: 0,
          positionLeft: 0,
          widthMode: 'fill',
          heightMode: 'fixed',
          width: 520,
          height: 220,
          sizeLimits: [],
          containerStyle: null,
          overflow: 'scroll',
          blur: null,
          transform: DEFAULT_TRANSFORM,
          flexShrink: 0,
        },
        defaultChildren: [
          createHorizontalListItemChildren(1),
          createHorizontalListItemChildren(2),
          createHorizontalListItemChildren(3),
        ],
      },
    ],
  },
  {
    type: 'list-vertical',
    craftType: 'VerticalList',
    label: '纵向列表',
    category: '列表组件',
    icon: iconListVertical,
    description: '带标题与列表项的纵向列表',
    isCanvas: true,
    defaultProps: {
      title: '列表标题',
      itemSpacing: 12,
      showItemNumber: false,
      dataMode: 'expression',
      expression: '',
      layout: { arrangement: 'vertical', spacingMode: 'fixed', spacing: 12, distribution: 'top-left', columnDistribution: 'left' },
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fill',
      heightMode: 'fit-content',
      width: 520,
      height: 360,
      sizeLimits: [],
      containerStyle: null,
      overflow: 'scroll',
      blur: null,
      transform: DEFAULT_TRANSFORM,
    },
    defaultChildren: [
      {
        type: 'Text',
        props: {
          verticalListRole: 'title',
          text: '列表标题',
          styleMode: 'custom',
          presetStyle: '24',
          fontSize: 24,
          fontWeight: 700,
          letterSpacing: 0,
          lineHeight: 32,
          textAlign: 'left',
          verticalAlign: 'center',
          color: '#ffffff',
          textShadow: null,
          maxLines: 1,
          positionType: 'relative',
          positionTop: 0,
          positionRight: 0,
          positionBottom: 0,
          positionLeft: 0,
          widthMode: 'fill',
          heightMode: 'fit-content',
          width: 520,
          height: 32,
          sizeLimits: [],
          containerStyle: null,
          overflow: 'hidden',
          transform: DEFAULT_TRANSFORM,
        },
      },
      {
        type: 'Container',
        isCanvas: true,
        props: {
          verticalListRole: 'items',
          layout: {
            arrangement: 'vertical',
            spacingMode: 'fixed',
            spacing: 12,
            distribution: 'top-left',
            columnDistribution: 'left',
          },
          positionType: 'relative',
          positionTop: 0,
          positionRight: 0,
          positionBottom: 0,
          positionLeft: 0,
          widthMode: 'fill',
          heightMode: 'fixed',
          width: 520,
          height: 300,
          sizeLimits: [],
          containerStyle: null,
          overflow: 'scroll',
          blur: null,
          transform: DEFAULT_TRANSFORM,
          flexShrink: 0,
        },
        defaultChildren: [
          createVerticalListItemChildren(1),
          createVerticalListItemChildren(2),
          createVerticalListItemChildren(3),
          createVerticalListItemChildren(4),
        ],
      },
    ],
  },
  {
    type: 'list-grid',
    craftType: 'GridList',
    label: '宫格列表',
    category: '列表组件',
    icon: iconListGrid,
    description: '带标题与卡片项的宫格列表',
    isCanvas: true,
    defaultProps: {
      title: '这是一个标题',
      gridListRole: 'items',
      columnCount: 2,
      columnGap: 20,
      rowGap: 20,
      dataMode: 'expression',
      expression: '',
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fill',
      heightMode: 'fit-content',
      width: 520,
      height: 560,
      sizeLimits: [],
      containerStyle: null,
      overflow: 'scroll',
      blur: null,
      transform: DEFAULT_TRANSFORM,
    },
    defaultChildren: [
      {
        type: 'Text',
        props: {
          gridListRole: 'title',
          text: '这是一个标题',
          styleMode: 'custom',
          presetStyle: '24',
          fontSize: 24,
          fontWeight: 700,
          letterSpacing: 0,
          lineHeight: 32,
          textAlign: 'left',
          verticalAlign: 'center',
          color: '#ffffff',
          textShadow: null,
          maxLines: 1,
          positionType: 'relative',
          positionTop: 0,
          positionRight: 0,
          positionBottom: 0,
          positionLeft: 0,
          widthMode: 'fill',
          heightMode: 'fit-content',
          width: 520,
          height: 32,
          sizeLimits: [],
          containerStyle: null,
          overflow: 'hidden',
          transform: DEFAULT_TRANSFORM,
        },
      },
      {
        type: 'Container',
        isCanvas: true,
        props: {
          gridListRole: 'items',
          layout: {
            arrangement: 'wrap',
            spacingMode: 'fixed',
            spacing: 20,
            distribution: 'top-left',
            columnDistribution: 'left',
            columnCount: 2,
            columnGap: 20,
            rowGap: 20,
          },
          positionType: 'relative',
          positionTop: 0,
          positionRight: 0,
          positionBottom: 0,
          positionLeft: 0,
          widthMode: 'fill',
          heightMode: 'fixed',
          width: 520,
          height: 500,
          sizeLimits: [],
          containerStyle: null,
          overflow: 'scroll',
          blur: null,
          transform: DEFAULT_TRANSFORM,
          flexShrink: 0,
        },
        defaultChildren: [
          createGridListItemChildren(1),
          createGridListItemChildren(2),
          createGridListItemChildren(3),
          createGridListItemChildren(4),
        ],
      },
    ],
  },

  /* ---- 输入组件 ---- */
  {
    type: 'input-button',
    craftType: 'Button',
    label: '按钮',
    category: '输入组件',
    icon: iconButton,
    description: '通用操作按钮',
    defaultProps: {
      variant: 'primary',
      showText: true,
      children: '点击操作',
      showIcon: false,
      iconName: '',
      iconColor: '#ffffff',
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fixed',
      heightMode: 'fixed',
      width: 132,
      height: 42,
      sizeLimits: [],
      containerStyle: null,
      transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
    },
  },
  {
    type: 'input-text',
    craftType: 'InputField',
    label: '输入框',
    category: '输入组件',
    icon: iconInput,
    description: '文本输入组件',
    defaultProps: {
      showLabel: true,
      label: '请输入文本',
      required: false,
      placeholder: '请输入内容',
      maxLengthEnabled: false,
      maxLength: 200,
      defaultValue: '',
      layout: 'vertical',
      labelWidth: 30,
      verticalAlign: 'top',
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fixed',
      heightMode: 'fixed',
      width: 240,
      height: 80,
      sizeLimits: [],
      containerStyle: null,
      transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
    },
  },
  {
    type: 'input-radio',
    craftType: 'RadioGroup',
    label: '单选',
    category: '输入组件',
    icon: iconRadio,
    description: '单选组件',
    defaultProps: {
      showLabel: true,
      label: '请选择',
      required: false,
      options: [
        { id: '1', label: '选项 1', value: 'option1', imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&h=300&fit=crop', description: '这是选项 1 的描述文字' },
        { id: '2', label: '选项 2', value: 'option2', imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400&h=300&fit=crop', description: '这是选项 2 的描述文字' },
        { id: '3', label: '选项 3', value: 'option3', imageUrl: null, description: '这是选项 3 的描述文字' },
      ],
      defaultValue: 'option1',
      displayStyle: 'horizontal',
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fixed',
      heightMode: 'fixed',
      width: 532,
      height: 245,
      sizeLimits: [],
      containerStyle: null,
      blur: null,
      transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
    },
  },
  {
    type: 'input-checkbox',
    craftType: 'CheckboxGroup',
    label: '多选',
    category: '输入组件',
    icon: iconCheckbox,
    description: '多选组件',
    defaultProps: {
      showLabel: true,
      label: '请选择',
      required: false,
      options: [
        { id: '1', label: '选项 1', value: 'option1', imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&h=300&fit=crop', description: '这是选项 1 的描述文字' },
        { id: '2', label: '选项 2', value: 'option2', imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400&h=300&fit=crop', description: '这是选项 2 的描述文字' },
        { id: '3', label: '选项 3', value: 'option3', imageUrl: null, description: '这是选项 3 的描述文字' },
      ],
      defaultValues: ['option1'],
      displayStyle: 'horizontal',
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fixed',
      heightMode: 'fixed',
      width: 532,
      height: 245,
      sizeLimits: [],
      containerStyle: null,
      blur: null,
      transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
    },
  },
  {
    type: 'input-number',
    craftType: 'NumberInput',
    label: '数字输入',
    category: '输入组件',
    icon: iconNumberInput,
    description: '数字输入组件',
    defaultProps: {
      showLabel: true,
      label: '数字输入',
      required: false,
      placeholder: '请输入数字',
      inputType: 'number',
      dataType: 'integer',
      decimalPlaces: 2,
      step: 1,
      defaultValue: null,
      layout: 'vertical',
      labelWidth: 30,
      verticalAlign: 'top',
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fixed',
      heightMode: 'fixed',
      width: 240,
      height: 80,
      sizeLimits: [],
      containerStyle: null,
      blur: null,
      transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
    },
  },
  {
    type: 'input-record',
    craftType: 'AudioRecorder',
    label: '录音',
    category: '输入组件',
    icon: iconAudioRecord,
    description: '音频录音组件',
    defaultProps: {
      maxDuration: 60,
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fixed',
      heightMode: 'fixed',
      width: 530,
      height: 100,
      sizeLimits: [],
      containerStyle: null,
      transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
    },
  },
  {
    type: 'input-camera',
    craftType: 'VideoRecorder',
    label: '录像',
    category: '输入组件',
    icon: iconVideoRecord,
    description: '视频录像组件',
    defaultProps: {
      maxDuration: 60,
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fixed',
      heightMode: 'fixed',
      width: 530,
      height: 100,
      sizeLimits: [],
      containerStyle: null,
      transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
    },
  },
  {
    type: 'input-menu',
    craftType: 'Form',
    label: '表单',
    category: '输入组件',
    icon: iconForm,
    description: '表单容器，支持内部组件编排',
    isCanvas: true,
    defaultProps: {
      formLayout: 'vertical',
      layout: { arrangement: 'vertical', spacingMode: 'fixed', spacing: 8, distribution: 'top-left', columnDistribution: 'left' },
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fill',
      heightMode: 'fit-content',
      width: 350,
      height: 320,
      sizeLimits: [],
      containerStyle: null,
      overflow: 'scroll',
      blur: null,
      transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
    },
    defaultChildren: [
      {
        type: 'Text',
        props: {
          text: '表单标题',
          styleMode: 'preset',
          presetStyle: '22',
          fontSize: 22,
          fontWeight: 500,
          letterSpacing: 0,
          lineHeight: null,
          textAlign: 'left',
          verticalAlign: 'top',
          color: null,
          textShadow: null,
          maxLines: null,
          positionType: 'relative',
          widthMode: 'fill',
          heightMode: 'fit-content',
          width: 160,
          height: 44,
          sizeLimits: [],
          containerStyle: null,
          overflow: 'visible',
          transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
        },
      },
      {
        type: 'Text',
        props: {
          text: '请填写以下信息',
          styleMode: 'preset',
          presetStyle: '14',
          fontSize: 14,
          fontWeight: 400,
          letterSpacing: 0,
          lineHeight: null,
          textAlign: 'left',
          verticalAlign: 'top',
          color: null,
          textShadow: null,
          maxLines: null,
          positionType: 'relative',
          widthMode: 'fill',
          heightMode: 'fit-content',
          width: 160,
          height: 28,
          sizeLimits: [],
          containerStyle: null,
          overflow: 'visible',
          transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
        },
      },
      {
        type: 'InputField',
        props: {
          showLabel: true,
          label: '请输入文本',
          required: false,
          placeholder: '请输入内容',
          maxLengthEnabled: false,
          maxLength: 200,
          defaultValue: '',
          layout: 'vertical',
          labelWidth: 30,
          verticalAlign: 'top',
          positionType: 'relative',
          widthMode: 'fill',
          heightMode: 'fixed',
          width: 240,
          height: 80,
          sizeLimits: [],
          containerStyle: null,
          transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
        },
      },
      {
        type: 'NumberInput',
        props: {
          showLabel: true,
          label: '数字输入',
          required: false,
          placeholder: '请输入数字',
          inputType: 'number',
          dataType: 'integer',
          decimalPlaces: 2,
          step: 1,
          defaultValue: null,
          layout: 'vertical',
          labelWidth: 30,
          verticalAlign: 'top',
          positionType: 'relative',
          widthMode: 'fill',
          heightMode: 'fixed',
          width: 240,
          height: 80,
          sizeLimits: [],
          containerStyle: null,
          blur: null,
          transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
        },
      },
      {
        type: 'Button',
        props: {
          variant: 'primary',
          showText: true,
          children: '提交',
          showIcon: false,
          iconName: '',
          iconColor: '#ffffff',
          positionType: 'relative',
          widthMode: 'fill',
          heightMode: 'fixed',
          width: 132,
          height: 42,
          sizeLimits: [],
          containerStyle: null,
          transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
        },
      },
    ],
  },

  /* ---- 展示组件 ---- */
  {
    type: 'display-text',
    craftType: 'Text',
    label: '文本',
    category: '展示组件',
    icon: iconText,
    description: '单行文本展示',
    defaultProps: {
      text: 'Text',
      styleMode: 'preset',
      presetStyle: '22',
      fontSize: 22,
      fontWeight: 500,
      letterSpacing: 0,
      lineHeight: null,
      textAlign: 'left',
      verticalAlign: 'top',
      color: null,
      textShadow: null,
      maxLines: null,
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fixed',
      heightMode: 'fixed',
      width: 160,
      height: 44,
      sizeLimits: [],
      containerStyle: null,
      overflow: 'visible',
      transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
    },
  },
  {
    type: 'display-audio',
    craftType: 'AudioDisplay',
    label: '音频',
    category: '展示组件',
    icon: iconAudio,
    description: '音频播放组件',
    defaultProps: {
      sourceType: 'local',
      audioUrl: null,
      bindingField: '',
      audioTitle: '音频标题',
      playerStyle: 'large',
      loop: false,
      preload: true,
      controlColor: null,
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fixed',
      heightMode: 'fixed',
      width: 280,
      height: 180,
      sizeLimits: [],
      containerStyle: null,
      blur: null,
      transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
    },
  },
  {
    type: 'display-video',
    craftType: 'VideoDisplay',
    label: '视频',
    category: '展示组件',
    icon: iconVideo,
    description: '视频播放组件',
    defaultProps: {
      sourceType: 'local',
      videoUrl: null,
      bindingField: '',
      videoTitle: '视频标题',
      fullscreen: false,
      loop: false,
      lazy: false,
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fixed',
      heightMode: 'fixed',
      width: 280,
      height: 180,
      sizeLimits: [],
      containerStyle: null,
      blur: null,
      transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
    },
  },
  {
    type: 'display-image',
    craftType: 'ImageDisplay',
    label: '图片',
    category: '展示组件',
    icon: iconImage,
    description: '图片展示组件',
    defaultProps: {
      sourceType: 'local',
      imageUrl: null,
      bindingField: '',
      fillMode: 'cover',
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fixed',
      heightMode: 'fixed',
      width: 200,
      height: 120,
      sizeLimits: [],
      containerStyle: null,
      blur: null,
      transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
    },
  },
  {
    type: 'display-carousel',
    craftType: 'CarouselDisplay',
    label: '轮播',
    category: '展示组件',
    icon: iconCarousel,
    description: '图片轮播组件',
    defaultProps: {
      contentMode: 'static',
      images: [
        { id: 'default_1', sourceType: 'local', imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&h=300&fit=crop', bindingField: '', fileName: '风景图1.jpg' },
        { id: 'default_2', sourceType: 'local', imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400&h=300&fit=crop', bindingField: '', fileName: '风景图2.jpg' },
      ],
      autoPlay: true,
      autoPlayInterval: 2,
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fixed',
      heightMode: 'fixed',
      width: 240,
      height: 132,
      sizeLimits: [],
      containerStyle: null,
      blur: null,
      transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
    },
  },
  {
    type: 'display-markdown',
    craftType: 'MarkdownDisplay',
    label: 'Markdown',
    category: '展示组件',
    icon: iconMarkdown,
    description: 'Markdown 文本展示',
    defaultProps: {
      content: `# 一级标题\n\n这是一段普通文本，用于展示 Markdown 的基本排版效果。\n\n## 二级标题\n\n### 三级标题\n\n1. 第一项有序列表\n2. 第二项有序列表\n3. 第三项有序列表\n\n[访问 XRFlow](https://xrflow.cn)\n\n![示例图片](https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=200&h=120&fit=crop)\n\n> 这是一段引用文本，用于展示引用样式的排版效果。`,
      textAlign: 'left',
      verticalAlign: 'top',
      color: null,
      maxLines: null,
      positionType: 'relative',
      positionTop: 0,
      positionRight: 0,
      positionBottom: 0,
      positionLeft: 0,
      widthMode: 'fixed',
      heightMode: 'fixed',
      width: 280,
      height: 320,
      sizeLimits: [],
      containerStyle: null,
      overflow: 'scroll',
      transform: { scale: 100, rotate: 0, translateX: 0, translateY: 0, skewX: 0, skewY: 0 },
    },
  },
];

const componentMap = new Map<ComponentDef['type'], RegistryItem>(
  COMPONENT_REGISTRY.map((component) => [component.type, component])
);

export const getComponentConfig = (type: string): RegistryItem | undefined =>
  componentMap.get(type);

export const createDragPayload = (
  type: string
): ComponentDragPayload | null => {
  const component = getComponentConfig(type);
  if (!component) return null;

  return {
    type: component.craftType,
    props: { ...(component?.defaultProps ?? {}) },
    isCanvas: component.isCanvas,
    defaultChildren: component.defaultChildren,
  };
};

export const encodeDragPayload = (payload: ComponentDragPayload): string =>
  JSON.stringify(payload);

export const decodeDragPayload = (
  input: string
): ComponentDragPayload | null => {
  try {
    const payload = JSON.parse(input) as ComponentDragPayload;

    if (!payload || typeof payload !== 'object') return null;
    if (!payload.type || typeof payload.type !== 'string') return null;
    if (!RESOLVER[payload.type]) return null;

    return {
      type: payload.type,
      props: payload.props ?? {},
      isCanvas: payload.isCanvas,
      defaultChildren: payload.defaultChildren,
    };
  } catch {
    return null;
  }
};
