import type { ComponentType } from 'react';
import {
  MdHome,
  MdMenu,
  MdMenuOpen,
  MdArrowBack,
  MdArrowForward,
  MdArrowUpward,
  MdArrowDownward,
  MdChevronLeft,
  MdChevronRight,
  MdExpandMore,
  MdExpandLess,
  MdClose,
  MdMoreVert,
  MdMoreHoriz,
  MdFullscreen,
  MdFullscreenExit,
  MdSearch,
  MdSettings,
  MdDelete,
  MdEdit,
  MdAdd,
  MdRemove,
  MdCheck,
  MdRefresh,
  MdShare,
  MdDownload,
  MdUpload,
  MdSave,
  MdSend,
  MdPrint,
  MdFilterList,
  MdSort,
  MdTune,
  MdDone,
  MdDoneAll,
  MdOpenInNew,
  MdContentCopy,
  MdContentPaste,
  MdContentCut,
  MdEmail,
  MdPhone,
  MdChat,
  MdNotifications,
  MdMessage,
  MdForum,
  MdFlag,
  MdBookmark,
  MdBookmarkBorder,
  MdLabel,
  MdLink,
  MdAttachFile,
  MdPlayArrow,
  MdPause,
  MdStop,
  MdSkipNext,
  MdSkipPrevious,
  MdVolumeUp,
  MdVolumeOff,
  MdImage,
  MdPhotoCamera,
  MdVideocam,
  MdMic,
  MdMicOff,
  MdPerson,
  MdGroup,
  MdPersonAdd,
  MdInfo,
  MdWarning,
  MdError,
  MdHelp,
  MdCheckCircle,
  MdCancel,
  MdAddCircle,
  MdRemoveCircle,
  MdLocationOn,
  MdMap,
  MdMyLocation,
  MdNavigation,
  MdPlace,
  MdCalendarToday,
  MdAccessTime,
  MdTimer,
  MdAlarm,
  MdSchedule,
  MdShoppingCart,
  MdStore,
  MdCreditCard,
  MdLocalOffer,
  MdLock,
  MdLockOpen,
  MdVisibility,
  MdVisibilityOff,
  MdSecurity,
  MdFingerprint,
  MdFolder,
  MdFolderOpen,
  MdCloudUpload,
  MdCloudDownload,
  MdCreateNewFolder,
  MdStar,
  MdStarBorder,
  MdFavorite,
  MdFavoriteBorder,
  MdThumbUp,
  MdThumbDown,
  MdDashboard,
  MdBarChart,
  MdPieChart,
  MdTrendingUp,
  MdTrendingDown,
  MdBuild,
  MdCode,
  MdBugReport,
  MdExtension,
  MdLightMode,
  MdDarkMode,
  MdWifi,
  MdBluetooth,
  MdGpsFixed,
  MdBatteryFull,
  MdPower,
  MdQrCode,
} from 'react-icons/md';

export interface IconEntry {
  /** 标准 Material Icon 名称，Android 端直接映射 Icons.Default.* */
  name: string;
  label: string;
  component: ComponentType<{ size?: number; color?: string }>;
}

export const CURATED_ICONS: IconEntry[] = [
  /* ---- 导航 ---- */
  { name: 'Home', label: '首页', component: MdHome },
  { name: 'Menu', label: '菜单', component: MdMenu },
  { name: 'MenuOpen', label: '展开菜单', component: MdMenuOpen },
  { name: 'ArrowBack', label: '返回', component: MdArrowBack },
  { name: 'ArrowForward', label: '前进', component: MdArrowForward },
  { name: 'ArrowUpward', label: '向上', component: MdArrowUpward },
  { name: 'ArrowDownward', label: '向下', component: MdArrowDownward },
  { name: 'ChevronLeft', label: '左箭头', component: MdChevronLeft },
  { name: 'ChevronRight', label: '右箭头', component: MdChevronRight },
  { name: 'ExpandMore', label: '展开', component: MdExpandMore },
  { name: 'ExpandLess', label: '收起', component: MdExpandLess },
  { name: 'Close', label: '关闭', component: MdClose },
  { name: 'MoreVert', label: '更多(竖)', component: MdMoreVert },
  { name: 'MoreHoriz', label: '更多(横)', component: MdMoreHoriz },
  { name: 'Fullscreen', label: '全屏', component: MdFullscreen },
  { name: 'FullscreenExit', label: '退出全屏', component: MdFullscreenExit },

  /* ---- 操作 ---- */
  { name: 'Search', label: '搜索', component: MdSearch },
  { name: 'Settings', label: '设置', component: MdSettings },
  { name: 'Delete', label: '删除', component: MdDelete },
  { name: 'Edit', label: '编辑', component: MdEdit },
  { name: 'Add', label: '添加', component: MdAdd },
  { name: 'Remove', label: '移除', component: MdRemove },
  { name: 'Check', label: '确认', component: MdCheck },
  { name: 'Refresh', label: '刷新', component: MdRefresh },
  { name: 'Share', label: '分享', component: MdShare },
  { name: 'Download', label: '下载', component: MdDownload },
  { name: 'Upload', label: '上传', component: MdUpload },
  { name: 'Save', label: '保存', component: MdSave },
  { name: 'Send', label: '发送', component: MdSend },
  { name: 'Print', label: '打印', component: MdPrint },
  { name: 'FilterList', label: '筛选', component: MdFilterList },
  { name: 'Sort', label: '排序', component: MdSort },
  { name: 'Tune', label: '调节', component: MdTune },
  { name: 'Done', label: '完成', component: MdDone },
  { name: 'DoneAll', label: '全部完成', component: MdDoneAll },
  { name: 'OpenInNew', label: '新窗口', component: MdOpenInNew },
  { name: 'ContentCopy', label: '复制', component: MdContentCopy },
  { name: 'ContentPaste', label: '粘贴', component: MdContentPaste },
  { name: 'ContentCut', label: '剪切', component: MdContentCut },

  /* ---- 通讯 ---- */
  { name: 'Email', label: '邮件', component: MdEmail },
  { name: 'Phone', label: '电话', component: MdPhone },
  { name: 'Chat', label: '聊天', component: MdChat },
  { name: 'Notifications', label: '通知', component: MdNotifications },
  { name: 'Message', label: '消息', component: MdMessage },
  { name: 'Forum', label: '论坛', component: MdForum },

  /* ---- 内容 ---- */
  { name: 'Flag', label: '标记', component: MdFlag },
  { name: 'Bookmark', label: '书签', component: MdBookmark },
  { name: 'BookmarkBorder', label: '书签(空)', component: MdBookmarkBorder },
  { name: 'Label', label: '标签', component: MdLabel },
  { name: 'Link', label: '链接', component: MdLink },
  { name: 'AttachFile', label: '附件', component: MdAttachFile },

  /* ---- 媒体 ---- */
  { name: 'PlayArrow', label: '播放', component: MdPlayArrow },
  { name: 'Pause', label: '暂停', component: MdPause },
  { name: 'Stop', label: '停止', component: MdStop },
  { name: 'SkipNext', label: '下一曲', component: MdSkipNext },
  { name: 'SkipPrevious', label: '上一曲', component: MdSkipPrevious },
  { name: 'VolumeUp', label: '音量', component: MdVolumeUp },
  { name: 'VolumeOff', label: '静音', component: MdVolumeOff },
  { name: 'Image', label: '图片', component: MdImage },
  { name: 'PhotoCamera', label: '相机', component: MdPhotoCamera },
  { name: 'Videocam', label: '录像', component: MdVideocam },
  { name: 'Mic', label: '麦克风', component: MdMic },
  { name: 'MicOff', label: '静音麦克', component: MdMicOff },

  /* ---- 人物 ---- */
  { name: 'Person', label: '用户', component: MdPerson },
  { name: 'Group', label: '用户组', component: MdGroup },
  { name: 'PersonAdd', label: '添加用户', component: MdPersonAdd },

  /* ---- 状态/提示 ---- */
  { name: 'Info', label: '信息', component: MdInfo },
  { name: 'Warning', label: '警告', component: MdWarning },
  { name: 'Error', label: '错误', component: MdError },
  { name: 'Help', label: '帮助', component: MdHelp },
  { name: 'CheckCircle', label: '成功', component: MdCheckCircle },
  { name: 'Cancel', label: '取消', component: MdCancel },
  { name: 'AddCircle', label: '添加(圆)', component: MdAddCircle },
  { name: 'RemoveCircle', label: '移除(圆)', component: MdRemoveCircle },

  /* ---- 位置 ---- */
  { name: 'LocationOn', label: '位置', component: MdLocationOn },
  { name: 'Map', label: '地图', component: MdMap },
  { name: 'MyLocation', label: '我的位置', component: MdMyLocation },
  { name: 'Navigation', label: '导航', component: MdNavigation },
  { name: 'Place', label: '地点', component: MdPlace },

  /* ---- 时间 ---- */
  { name: 'CalendarToday', label: '日历', component: MdCalendarToday },
  { name: 'AccessTime', label: '时间', component: MdAccessTime },
  { name: 'Timer', label: '计时器', component: MdTimer },
  { name: 'Alarm', label: '闹钟', component: MdAlarm },
  { name: 'Schedule', label: '日程', component: MdSchedule },

  /* ---- 商业 ---- */
  { name: 'ShoppingCart', label: '购物车', component: MdShoppingCart },
  { name: 'Store', label: '商店', component: MdStore },
  { name: 'CreditCard', label: '银行卡', component: MdCreditCard },
  { name: 'LocalOffer', label: '优惠', component: MdLocalOffer },

  /* ---- 安全 ---- */
  { name: 'Lock', label: '锁定', component: MdLock },
  { name: 'LockOpen', label: '解锁', component: MdLockOpen },
  { name: 'Visibility', label: '可见', component: MdVisibility },
  { name: 'VisibilityOff', label: '隐藏', component: MdVisibilityOff },
  { name: 'Security', label: '安全', component: MdSecurity },
  { name: 'Fingerprint', label: '指纹', component: MdFingerprint },

  /* ---- 文件 ---- */
  { name: 'Folder', label: '文件夹', component: MdFolder },
  { name: 'FolderOpen', label: '打开文件夹', component: MdFolderOpen },
  { name: 'CloudUpload', label: '云上传', component: MdCloudUpload },
  { name: 'CloudDownload', label: '云下载', component: MdCloudDownload },
  { name: 'CreateNewFolder', label: '新建文件夹', component: MdCreateNewFolder },

  /* ---- 收藏/评价 ---- */
  { name: 'Star', label: '星标', component: MdStar },
  { name: 'StarBorder', label: '星标(空)', component: MdStarBorder },
  { name: 'Favorite', label: '收藏', component: MdFavorite },
  { name: 'FavoriteBorder', label: '收藏(空)', component: MdFavoriteBorder },
  { name: 'ThumbUp', label: '点赞', component: MdThumbUp },
  { name: 'ThumbDown', label: '踩', component: MdThumbDown },

  /* ---- 数据 ---- */
  { name: 'Dashboard', label: '仪表盘', component: MdDashboard },
  { name: 'BarChart', label: '柱状图', component: MdBarChart },
  { name: 'PieChart', label: '饼图', component: MdPieChart },
  { name: 'TrendingUp', label: '上升', component: MdTrendingUp },
  { name: 'TrendingDown', label: '下降', component: MdTrendingDown },

  /* ---- 开发 ---- */
  { name: 'Build', label: '工具', component: MdBuild },
  { name: 'Code', label: '代码', component: MdCode },
  { name: 'BugReport', label: '报告', component: MdBugReport },
  { name: 'Extension', label: '插件', component: MdExtension },

  /* ---- 设备/系统 ---- */
  { name: 'LightMode', label: '亮色', component: MdLightMode },
  { name: 'DarkMode', label: '暗色', component: MdDarkMode },
  { name: 'Wifi', label: 'WiFi', component: MdWifi },
  { name: 'Bluetooth', label: '蓝牙', component: MdBluetooth },
  { name: 'GpsFixed', label: 'GPS', component: MdGpsFixed },
  { name: 'BatteryFull', label: '电量', component: MdBatteryFull },
  { name: 'Power', label: '电源', component: MdPower },
  { name: 'QrCode', label: '二维码', component: MdQrCode },
];

const ICON_MAP = new Map(CURATED_ICONS.map((i) => [i.name, i]));

export const getIconComponent = (
  name: string
): ComponentType<{ size?: number; color?: string }> | null =>
  ICON_MAP.get(name)?.component ?? null;
